### ISSUE TITLE
cmmdline tool demo not working

### ISSUE THREAD

**Issue by markrans** [hcebke/libQEx#4] opened 2016-09-22 17:58 UTC
Hi, the repo builds without errors but the demo never completes, hanging indefinitely at:
MeshDecimator::decimate() collapsed __ edges.
Output prior to the halting includes:
ERROR in transition function: 9.22337e+18
ERROR in inverse transition function: 9.22337e+18
constructed 157 valid transition functions -> 29 invalid ones
test exactness of transition functions before preprocessing...
... done!
found 186 inexact transitions in input with max deviation 9.22337e+18
QuadMeshExtraction Preprocess maxmial uv deviaton: 4.29497e+10
test exactness of transition functions...
ERROR: values are not identical after preprocessing, diffs are (6.44245e+09,6.44245e+09) and (0,0)
Collapsing inconsistent edge. Length of he0 = 0, length of he1 = 3.68935e+19
If this happens prior to truncation it's ok. If it happens afterwards, this is a bug.

I have OpenMesh installed. What exactly is meant when you refer to the path to OpenMesh binaries? Any assistance in this installation would be greatly appreciated as I'd love to use this technique in my research. Thanks.

**Comment by hcebke** [comment] 2016-09-23 06:50
Since the demo is running, everything seems to be linked just fine, so it's not an issue with OpenMesh. Could you attach the mesh you ran the demo on so that I can reproduce the error?

**Comment by hcebke** [comment] 2016-10-25 09:23
I'm closing this issue since I'm unable to reproduce it without the mesh that caused it.

**Closed by hcebke** 2016-10-25 09:23 UTC
